# Generated by Django 5.2.4 on 2025-07-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='city',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
