# Generated by Django 5.2.4 on 2025-07-20 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_team_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.team'),
        ),
    ]
