# Generated by Django 5.2.4 on 2025-07-22 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_division_team_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='playingToday',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.PositiveIntegerField(),
        ),
    ]
