# Generated by Django 5.2.4 on 2025-07-22 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_player_playingtoday_alter_player_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('founded', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='description',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
