# Generated by Django 5.2.4 on 2025-07-22 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_news_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='statistic',
            name='draws',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
