# Generated by Django 5.2.4 on 2025-07-22 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_statistic_draws'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='lose',
            new_name='losses',
        ),
        migrations.RenameField(
            model_name='statistic',
            old_name='win',
            new_name='wins',
        ),
    ]
