# Generated by Django 5.2.4 on 2025-07-22 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_lose_statistic_losses_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='statistic',
            old_name='gamePlayed',
            new_name='gamesPlayed',
        ),
    ]
